Repository Charlie059/Flow.IO, pull requests merged in 2024-02, with the labels that each got.

#20 chore: add `.idea` to .gitignore file
  .gitignore
Labels: size:XS, lgtm

#22 Fi 46 add stripe
  @core/cms/docker/app/Dockerfile
  @core/cms/src/external-auth-integration/auth-provider.factory.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/oauth2.module.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/stripe/stripe.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/stripe/stripe.service.ts
Labels: size:L, lgtm

#23 FI-46 refactor(directory): rename stripe folder to stripe/v1
  @core/cms/src/external-auth-integration/auth-provider.factory.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/oauth2.module.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/stripe/v1/stripe.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/stripe/v1/stripe.service.ts
Labels: size:S, lgtm
