Repository Charlie059/Flow.IO, pull requests merged in 2024-01, with the labels that each got.

#9 feat: Add GitHub oauth
  @core/cms/src/app.controller.ts
  @core/cms/src/database-integration/database-integration.service.ts
  @core/cms/src/external-auth-integration/auth-provider.factory.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/@types/index.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/github/v2/github.oauth.v2.service.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/github/v2/github.v2.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/google/v2/google.v2.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/oauth2.module.ts
Labels: enhancement, size:L, lgtm

#7 refactor: Refactor CMS codes
  @core/cms/.editorconfig
  @core/cms/src/external-auth-integration/auth-callback.controller.ts
  @core/cms/src/external-auth-integration/auth-provider.factory.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/@types/index.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/github/v1/github.v1.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/github/v1/github.v1.service.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/google/v2/google.v2.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/google/v2/google.v2.service.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/interface/ioauth.interface.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/oauth2.module.ts
  @core/cms/src/external-auth-integration/external-auth-integration.module.ts
  @core/cms/src/external-auth-integration/utils/index.ts
  @core/cms/tsconfig.json
Labels: size:L, lgtm

#11 docs: Add a draft Readme to CMS (FI-16)
  @core/cms/.env.example
  @core/cms/README.md
Labels: documentation, size:L, lgtm

#16 fix: change ICredentials to IClientCredentials
  @core/cms/src/external-auth-integration/auth-providers/oauth2/@types/index.ts
Labels: enhancement

#17 feat(oauth): Fi-38 Add slack v2 OAuth2 to CMS
  @core/cms/src/app.controller.ts
  @core/cms/src/external-auth-integration/auth-provider.factory.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/oauth2.module.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/slack/v2/slack.v2.config.ts
  @core/cms/src/external-auth-integration/auth-providers/oauth2/slack/v2/slack.v2.service.ts
  @core/cms/src/external-auth-integration/utils/index.ts
Labels: size:L
